language: cpp
compiler: [clang, gcc]
sudo: true
before_install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake=3.2.3-5ppa5~precise1

before_script: cmake .
script: make
