dist: bionic
sudo: false

language: cpp
compiler: [clang, gcc]
install: if [ "$CXX" = "g++" ]; then export CXX="g++-7.5" CC="gcc-7.5"; fi
addons:
  apt:
    sources: [ubuntu-toolchain-r-test]
    packages: [gcc-7.5, g++-7.5, clang, cmake, zlib1g-dev]
before_script: cmake .
script: make
