language: cpp
compiler: [clang, gcc]
sudo: true
before_install:
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake -y

before_script: cmake .
script: make
