dist: bionic

language: cpp
compiler: [clang, gcc]

install: if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
addons:
  apt:
    sources: [ubuntu-toolchain-r-test]
    packages: [gcc-7, g++-7, clang, cmake, zlib1g-dev]
before_script: cmake .
script: make
